### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by jotarothe** [Anistream/Anistream-Mobile#8] opened 2020-04-07 12:34 UTC
It worked fine before but now it redirects to some other website.

**Comment by ColaFan69** [comment] 2020-04-07 15:18
I have the same issue. I wonder what is going on.

**Comment by GoluLiliput** [comment] 2020-04-07 16:08
Yes now that's some issue... m facing the same bro

**Comment by Riku32** [comment] 2020-04-09 04:19
FIxed

**Comment by GoluLiliput** [comment] 2020-04-09 04:48
No the issue is not fixed @Riku32

**Comment by GoluLiliput** [comment] 2020-04-09 04:49
It still shows external page selection with bunch of list of servers

**Comment by Riku32** [comment] 2020-04-09 04:51
Did you read the thing that says "We are fixing this problem"

**Comment by Riku32** [comment] 2020-04-09 04:51
Just wait a few hours

**Comment by GoluLiliput** [comment] 2020-04-09 04:57
Ok thanks a lot @Riku32

**Comment by CR4KE** [comment] 2020-04-11 19:13
Still get the " if main servers can't load please change to other server, we are fixing this problem, thank you"

**Comment by Doomslayer-101** [comment] 2020-04-13 03:29
Same here too

**Comment by GoluLiliput** [comment] 2020-04-13 03:34
It's not the app problem... It's rgebserver problem. This app's development is stopped and we can't expect any update or fixes on this app by the developper, bcz he s an idiot n doesn't knw anythng lol

**Comment by Riku32** [comment] 2020-04-13 03:49
It will be fixed if the scrape sources fix their shit, I stopped development because I lost motivation and got a DMCA. Learn english before attempting to insult me :3

**Comment by GoluLiliput** [comment] 2020-04-13 04:39
So the app will retrn to the original state once the server is fixed? It won't show the page where we see the server selection shit agn?

**Comment by CR4KE** [comment] 2020-04-13 09:28
I think they're saying, it might not get fixed if they don't fix the server 😔 
Any good alternative apps?

**Comment by GoluLiliput** [comment] 2020-04-13 09:41
Yes bro... Search for Animestack 2020 on playstore ro google it. U will love the app like hell😍😍😍

**Comment by GoluLiliput** [comment] 2020-04-13 09:44
> I think they're saying, it might not get fixed if they don't fix the server 😔 
> Any good alternative apps?

Download... Animestack 2020 from playstore or Google. I assure u wl love the app. U can thank me later for it😉

**Comment by CR4KE** [comment] 2020-04-13 09:47
Cheers will give it a try 😁

**Closed** 2020-04-13 20:00 UTC
